export const loadingMessages = `
"Calibrating the hyperdrive with unicorn whispers."
"Translating alien emojis into Earthly emotions."
"Dancing the binary code at the intergalactic disco."
"Inflating space bubbles for zero-gravity pillow fights."
"Convincing black holes to join a sing-along choir."
"Wrestling quantum particles for a game of subatomic tag."
"Tickling extraterrestrial amoebas just for kicks."
"Polishing time-travel mirrors to see reflections from tomorrow."
"Juggling antimatter snowflakes in a cosmic blizzard."
"Babysitting baby star clusters during naptime."
"Bottling the laughter of wormholes for later enjoyment."
"Teaching interstellar crabs the moonwalk."
"Balancing the cosmic equation with rubber duckies."
"Dusting off ancient alien artifacts with laser feather dusters."
"Organizing a parallel universe hide-and-seek tournament."
"Playing hide-and-seek with Schroedinger's cat in a teleportation maze."
"Negotiating peace treaties between parallel universe pandas and robots."
"Training intergalactic snails for the great space race."
"Herding quantum sheep through the fabric of spacetime."
"Reciting Vogon poetry in an attempt to repel invaders."
"Hosting a telepathic tea party for sentient clouds."
"Coaxing malfunctioning robots with lullabies and oil massages."
"Moonwalking on the event horizon of a cosmic donut."
"Conducting a symphony of alien frequencies with a light saber baton."
"Negotiating a trade deal between time-traveling pirates and space ninjas."
"Babbling in an ancient alien dialect to confuse rogue AIs."
"Playing hopscotch on the rings of Saturn with zero-gravity boots."
"Befriending interdimensional dolphins fluent in binary."
"Convincing dark matter to attend a glow-in-the-dark party."
"Practicing levitation with levitating space jellyfish."
"Hitching a ride on a comet while juggling star clusters."
"Teaching a robot dance crew the art of emotional expression."
"Summoning UFOs with interpretative dance rituals."
"Creating crop circles in zero-gravity fields with tractor beams."
"Impersonating a solar flare to confuse sunspot observers."
"Diplomacy with alien diplomats through interpretive dance-offs."
"Playing chess with a sentient nebula and losing gracefully."
"Negotiating peace treaties between time-traveling dinosaurs and future robots."
"Building sandcastles on exoplanets with cosmic ocean waves."
"Conducting an orchestra of alien bug symphonies."
"Teleporting through dimensions with a rainbow-colored pogo stick."
"Translating Morse code messages from extraterrestrial fireflies."
"Attending a zero-gravity synchronized swimming competition."
"Participating in a relay race across the rings of Jupiter."
"Defying gravity by hosting upside-down picnics on magnetic asteroids."
"Exchanging love letters with parallel universe versions of oneself."
"Negotiating with interdimensional diplomats using interpretive dance diplomacy."
"Playing hide-and-seek with the shadows of dark matter."
"Having a tea party with time-traveling dinosaurs and robot butlers."
"Juggling quantum entangled particles while riding a quantum unicycle."
"Hosting a holographic game night with ghostly entities."
"Impersonating a comet to get a front-row seat at a cosmic concert."
"Negotiating peace treaties between time-traveling pirates and space ninjas."
"Having a conversation with extraterrestrial rock formations using telepathic vibrations."
"Playing hide-and-seek with Schroedinger's cat in a teleportation maze."
"Participating in a zero-gravity synchronized swimming competition."
"Attempting to communicate with intergalactic space chickens using semaphore signals."
"Building sandcastles on exoplanets with cosmic ocean waves."
"Convincing black holes to participate in a gravity-defying dance-off."
"Befriending time-traveling flamingos in a temporal oasis."
"Wrestling quantum particles for a game of subatomic tag."
"Polishing the interstellar mirror for a reflection of parallel selves."
"Organizing a parallel universe hide-and-seek tournament."
"Playing chess with a sentient nebula and losing gracefully."
"Hosting a telepathic tea party for sentient clouds."
"Creating crop circles in zero-gravity fields with tractor beams."
"Negotiating with interdimensional diplomats using interpretive dance diplomacy."
"Conducting an orchestra of alien bug symphonies."
"Summoning UFOs with interpretative dance rituals."
"Building sandcastles on exoplanets with cosmic ocean waves."
"Practicing levitation with levitating space jellyfish."
"Attending a zero-gravity synchronized swimming competition."
"Participating in a relay race across the rings of Jupiter."
"Defying gravity by hosting upside-down picnics on magnetic asteroids."
"Negotiating peace treaties between time-traveling dinosaurs and future robots."
"Juggling quantum entangled particles while riding a quantum unicycle."
"Having a tea party with time-traveling dinosaurs and robot butlers."
"Negotiating with interdimensional diplomats using interpretive dance diplomacy."
"Playing hide-and-seek with the shadows of dark matter."
"Exchanging love letters with parallel universe versions of oneself."
"Impersonating a comet to get a front-row seat at a cosmic concert."
"Negotiating peace treaties between time-traveling pirates and space ninjas."
"Having a conversation with extraterrestrial rock formations using telepathic vibrations."
"Playing hide-and-seek with Schroedinger's cat in a teleportation maze."
"Participating in a zero-gravity synchronized swimming competition."
"Attempting to communicate with intergalactic space chickens using semaphore signals."
"Building sandcastles on exoplanets with cosmic ocean waves."
"Convincing black holes to participate in a gravity-defying dance-off."
"Befriending time-traveling flamingos in a temporal oasis."
"Wrestling quantum particles for a game of subatomic tag."
"Polishing the interstellar mirror for a reflection of parallel selves."
"Organizing a parallel universe hide-and-seek tournament."
"Playing chess with a sentient nebula and losing gracefully."
"Hosting a telepathic tea party for sentient clouds."
"Creating crop circles in zero-gravity fields with tractor beams."
"Negotiating with interdimensional diplomats using interpretive dance diplomacy."
"Conducting an orchestra of alien bug symphonies."
"Summoning UFOs with interpretative dance rituals."
"Building sandcastles on exoplanets with cosmic ocean waves."
"Practicing levitation with levitating space jellyfish."
`
    .split(`\n`)
    .map((x) => x.trim().replace(/"/g, ``))
    .filter((x) => x)
